--列出總程式數
SELECT UTP_TXN_ID, B.TXN_NAME FROM UTP A LEFT JOIN TXN B ON A.UTP_TXN_ID = B.TXN_ID
WHERE TXN_NAME IS NOT NULL
GROUP BY UTP_TXN_ID, B.TXN_NAME

UNION

SELECT TXN_ID, TXN_NAME FROM CI.TXN
WHERE  COALESCE(TXN_DEFAULT,'') = 'Y'

ORDER BY UTP_TXN_ID

--各部門程式數
--同一隻程式可能會同時出現在不同部門，故與總程式數不會相符
SELECT
CASE WHEN SUBSTR(UTP_USER_ID,1,1) = 'C' THEN '結算部'   
     WHEN SUBSTR(UTP_USER_ID,1,1) = 'T' THEN '交易部'   
     WHEN SUBSTR(UTP_USER_ID,1,1) = 'J' THEN '資規部'   
     WHEN SUBSTR(UTP_USER_ID,1,1) = 'I' THEN '資作部'   
     WHEN SUBSTR(UTP_USER_ID,1,1) = 'W' THEN '監視部'
     WHEN SUBSTR(UTP_USER_ID,1,1) = 'B' THEN '企劃部'
END  AS DEPARTMENT ,
UTP_TXN_ID, B.TXN_NAME FROM UTP A LEFT JOIN TXN B ON A.UTP_TXN_ID = B.TXN_ID
WHERE TXN_NAME IS NOT NULL
GROUP BY SUBSTR(UTP_USER_ID,1,1), UTP_TXN_ID, B.TXN_NAME
ORDER BY DEPARTMENT, UTP_TXN_ID